# Generated by Django 4.2 on 2023-05-24 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtributoClasseProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Criado em')),
                ('nome', models.CharField(max_length=24, verbose_name='Nome Atributo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Criado em')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClasseProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Criado em')),
                ('nome', models.CharField(max_length=64, verbose_name='Classe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Criado em')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('descricao', models.TextField(max_length=255, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='catalogo.classeproduto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValorAtributoClasseProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Criado em')),
                ('valor', models.CharField(max_length=255, verbose_name='Valor')),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.atributoclasseproduto')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='catalogo.produto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImagemProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Criado em')),
                ('nome', models.CharField(verbose_name='Nome da Imagem')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('arquivo', models.ImageField(upload_to='', verbose_name='Arquivo')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='catalogo.produto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Criado em')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.categoria')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.produto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='atributoclasseproduto',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atributos', to='catalogo.classeproduto'),
        ),
    ]
