# Generated by Django 4.2 on 2023-05-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField()),
                ('genero', models.CharField(choices=[('DRAMA', 'DRAMA'), ('COMEDIA', 'COMÉDIA'), ('AVENTURA', 'AVENTURA')])),
                ('ano', models.PositiveIntegerField()),
                ('duracao', models.PositiveIntegerField()),
            ],
        ),
    ]
